-- PostgreSQL version 10+
--  CREATE TABLE sketch(
  --  ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  --  AUTHOR VARCHAR(255) DEFAULT 'Anonymous' NOT NULL,
  --  TITLE VARCHAR(255) DEFAULT 'Untitled' NOT NULL,
  --  IMAGE VARCHAR(1024) NOT NULL,
  --  CREATED_AT TIMESTAMP DEFAULT NOW()
--  );

CREATE DATABASE rubymvc;

CREATE TABLE sketch(
  id SERIAL PRIMARY KEY,
  author VARCHAR(255) DEFAULT 'Anonymous' NOT NULL,
  title VARCHAR(255) DEFAULT 'Untitled' NOT NULL,
  image VARCHAR(1024) NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);
